function picture(item,parent){const photo=photos.get(item.id);if(photo&&/^previews\/[A-Za-z0-9_-]+\.png$/.test(photo.preview||'')){const img=make('img');img.src=photo.preview;img.alt=item.name;img.loading='lazy';img.onclick=()=>viewPictures([item]);parent.append(img);}else parent.append(make('div','photo-placeholder','预览未生成 · 可打开原图'));}
function renderPhotos(){if(!data)return;$('photo-wall').replaceChildren();if($('view-mode').value!=='wall')return;for(const item of pageItems){const card=make('article','photo-card');picture(item,card);const label=make('label'),check=make('input');check.type='checkbox';check.checked=selected.has(item.id);check.disabled=saving||operating||handledTrash.has(item.path);check.setAttribute('aria-label','选择照片 '+item.name);check.onchange=()=>{if(check.checked)selected.add(item.id);else selected.delete(item.id);updateSelection();};label.append(check,make('strong','',item.name));card.append(label,make('div','path',item.path),make('div','muted',`${fileSize(item.bytes)} · ${(photos.get(item.id)||{}).month||'日期未提供'} · ${names[item.state]}`),make('div','reason',item.reason));if(handledTrash.has(item.path))card.append(make('p','warning','已移到废纸篓，请重新扫描更新清单'));if(item.duplicate_group)card.append(make('span','badge warning','精确重复第 '+item.duplicate_group+' 组'));if(mediaIds[item.path])for(const[action,text]of[['open','打开原图'],['reveal','在 Finder 定位']]){const button=make('button','',text);button.disabled=saving||operating||handledTrash.has(item.path);button.setAttribute('aria-label',text+' '+item.name);button.onclick=()=>openMedia(item,action,button);card.append(button);}const edit=make('button','','调整分类位置');edit.disabled=saving||operating;edit.onclick=()=>openEditor(item);card.append(edit);$('photo-wall').append(card);}if(!pageItems.length)$('photo-wall').append(make('p','empty','没有符合条件的照片。'));}
function viewPictures(items){$('picture-title').textContent=items.length===2?'并排比较照片':'照片预览';$('picture-body').replaceChildren();const grid=make('div',items.length===2?'compare-pictures':'');for(const item of items){const cell=make('div');picture(item,cell);cell.append(make('div','path',item.path));if(mediaIds[item.path]){const button=make('button','','打开原图');button.onclick=()=>openMedia(item,'open',button);cell.append(button);}grid.append(cell);}$('picture-body').append(grid);if(!$('picture-viewer').open)$('picture-viewer').showModal();}
$('select-all-current').onclick=()=>{const items=pageItems.filter(item=>!handledTrash.has(item.path)),all=items.every(item=>selected.has(item.id));for(const item of items){if(all)selected.delete(item.id);else selected.add(item.id);}render();};
$('picture-close').onclick=()=>$('picture-viewer').close();$('compare').onclick=()=>viewPictures(data.items.filter(item=>selected.has(item.id)));
$('view-mode').onchange=()=>{page=0;selected.clear();render();};
function optionsFor(id,values,label){$(id).replaceChildren();const all=make('option','',label);all.value='';$(id).append(all);for(const value of [...new Set(values)].filter(Boolean).sort().slice(0,1000)){const option=make('option','',value);option.value=value;$(id).append(option);}}
async function api(route,body){const response=await fetch(route,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{});const result=await response.json();if(!response.ok)throw new Error(result.error||'请求失败');return result;}
async function checkDisks(){try{const result=await api('api/roots');$('disk-status').replaceChildren();for(const root of result.roots)$('disk-status').append(make('p','',`${root.status==='available'?'来源可访问':'来源不可访问（磁盘未连接、文件夹移走或权限问题）'}：${root.path}`));}catch(err){$('disk-status').textContent=err.message;}}
$('check-disks').onclick=checkDisks;
async function loadExtras(){const results=await Promise.allSettled([api('api/photos'),api('api/changes')]);if(results[0].status==='fulfilled'){const items=results[0].value.items;photos=new Map(items.map(item=>[item.id,item]));optionsFor('photo-month',items.map(item=>item.month),'全部照片年月');render();}else error('照片清单读取失败：'+results[0].reason.message);if(results[1].status==='fulfilled'){const result=results[1].value;const labels={added:'新增',changed:'发生变化',absent:'本次未扫描到'};$('changes-list').replaceChildren();$('changes-list').append(make('p','',result.message||`对比 ${result.previous_created_at}：新增 ${result.counts.added} · 变化 ${result.counts.changed} · 本次未扫描到 ${result.counts.absent}`));for(const item of result.items.slice(0,200))$('changes-list').append(make('p','path',labels[item.state]+'：'+item.path));if(result.items.length>200)$('changes-list').append(make('p','','仅展示前 200 项。'));}else $('changes-list').textContent='比较失败：'+results[1].reason.message;checkDisks();refreshOperations();}
const oldBuildFolders=buildFolders;buildFolders=function(){oldBuildFolders();optionsFor('source-folder',data.items.map(item=>item.path.slice(0,item.path.lastIndexOf('/'))),'全部原文件夹');};
$('choose-destination').onclick=async()=>{const button=$('choose-destination');button.disabled=true;try{const result=await api('api/operations/destination',{});if(result.destination)$('destination').value=result.destination;}catch(err){error(err.message);}finally{button.disabled=false;}};
async function previewOperation(mode){if(operating||saving||!selected.size)return;saving=true;error();$('notice').textContent='正在检查文件和目标位置…';render();try{executionPreview=await api('api/operations/preview',{mode,ids:[...selected],destination:$('destination').value.trim()});$('execution-title').textContent=mode==='copy'?'确认复制到分类目录':'确认移到废纸篓';$('execution-summary').textContent=`${executionPreview.items.length} 个文件 · ${fileSize(executionPreview.bytes)} · ${mode==='copy'?'复制后保留原件，目标副本使用 SHA-256 校验':'从原位置移到 macOS 废纸篓，可在 Finder 恢复；占用空间不一定立即释放'}`;$('execution-items').replaceChildren();for(const item of executionPreview.items){const row=make('li');row.append(make('div','path',item.path),make('div','path','→ '+item.target));$('execution-items').append(row);}$('execution-confirm').checked=false;$('execution-start').disabled=true;$('execution-error').hidden=true;$('execution').showModal();$('notice').textContent='检查完成，请在弹窗中核对。';}catch(err){error(err.message);$('notice').textContent='';}finally{saving=false;render();}}
$('copy-files').onclick=()=>previewOperation('copy');$('trash-files').onclick=()=>previewOperation('trash');
$('execution-confirm').onchange=()=>$('execution-start').disabled=!$('execution-confirm').checked||operating;
$('execution-cancel').onclick=()=>{executionPreview=null;$('execution').close();};
$('execution').addEventListener('cancel',event=>{if(operating)event.preventDefault();else executionPreview=null;});
$('execution-start').onclick=async()=>{if(!executionPreview||!$('execution-confirm').checked||operating)return;operating=true;$('execution-start').disabled=true;$('execution-cancel').disabled=true;try{const job=await api('api/operations/start',{token:executionPreview.token});executionPreview=null;$('execution').close();selected.clear();$('notice').textContent='操作已开始，请保持本机服务运行，完成后重新扫描。';pollOperation(job.id);}catch(err){$('execution-error').hidden=false;$('execution-error').textContent=err.message;operating=false;$('execution-start').disabled=false;}finally{$('execution-cancel').disabled=false;render();}};
function operationCard(job){const box=make('div','operation'),state={running:'执行中',complete:'已完成',stopped:'已停止',interrupted:'服务曾中断'};box.append(make('strong','',`${job.mode==='copy'?'复制分类':'废纸篓清理'} · ${state[job.status]||job.status} · ${job.items.filter(item=>item.status==='success').length}/${job.total}`),make('p','muted',job.created_at||''));if(job.error)box.append(make('p','warning',job.error));for(const item of job.items){const text=make('pre','',`${item.status==='success'?'成功':item.status==='processing'?(job.status==='running'?`正在${({copying:'复制',verifying:'校验副本',verified:'完成校验'})[item.phase]||'处理'}${job.mode==='copy'?'（'+fileSize(item.processed_bytes||0)+' / '+fileSize(item.bytes||0)+'）':''}`:'处理结果待确认'):item.status==='unknown'?'结果未确认':'失败'}：${item.path}\n→ ${item.trashed_path||item.target}${item.error?'\n'+item.error:''}`);box.append(text);}box.append(make('p','muted','记录保存在本次报告的 operations 文件夹。已成功项不会自动撤销；结果未确认时先在 Finder 核对。'));return box;}
async function refreshOperations(){try{const result=await api('api/operations');$('operations').replaceChildren();for(const job of result.jobs){if(job.mode==='trash')for(const item of job.items)if(item.status==='success')handledTrash.add(item.path);$('operations').append(operationCard(job));}render();if(!result.jobs.length)$('operations').append(make('p','','本次扫描还没有文件操作记录。'));}catch(err){$('operations').textContent='记录读取失败：'+err.message;}}
$('refresh-operations').onclick=refreshOperations;
async function pollOperation(id){clearTimeout(operationTimer);try{const job=await api('api/operations/'+id);$('operations').replaceChildren(operationCard(job));if(job.status==='running'){operationTimer=setTimeout(()=>pollOperation(id),1000);return;}operating=false;if(job.mode==='trash')for(const item of job.items)if(item.status==='success')handledTrash.add(item.path);$('notice').textContent=job.status==='complete'?'操作完成，请重新扫描更新文件清单。':'操作已停止，请查看逐项结果；成功项保留。';render();}catch(err){operating=false;error('无法读取操作结果，请先核对记录和 Finder：'+err.message);render();}}
